- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-name-mail-carrier
  startingGear: MailCarrierGear
  playTimeTracker: JobMailCarrier
  icon: "MailCarrier"
  supervisors: job-supervisors-hop
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadMailCarrier
    jumpsuit: ClothingUniformMailCarrier
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
  innerclothingskirt: ClothingUniformSkirtMailCarrier
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
