- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    shoes: ClothingShoesSpaceNinja
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterWinterCentcom
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: RubberStampCentcom
    pocket2: Paper
    socks: ClothingUndercandycaneg_knee
    underpants: ClothingUnderboxers_striped
    # undershirt:
