- type: job
  id: SecurityCadet
  name: "peace keeper"
  setPreference: true
  playTimeTracker: JobSecurityCadet
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    head: ClothingHeadHatSecsoft
    jumpsuit: ClothingUniformJumpsuitSecBlue
    eyes: ClothingEyesGlassesSecurity
    pocket1: Handcuffs
    pocket2: Handcuffs
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: WeaponDisabler
  innerclothingskirt: ClothingUniformJumpsuitSecBlue
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
