- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 18000
#      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  whitelistRequired: true
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
