- type: department
  id: Civilian
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - Gladiator
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - MailCarrier
  - MedicalIntern
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - ServiceWorker
  - TechnicalAssistant
  - Quartermaster
  - Prisoner

- type: department
  id: Command
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ERTEngineer
  - ERTJanitor
  - ERTLeader
  - ERTMedical
  - ERTSecurity
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Mystagogue

- type: department
  id: Engineering
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  - SalvageTechnician

- type: department
  id: Medical
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - MedicalCyborg
  - Paramedic

- type: department
  id: Security
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden

- type: department
  id: Epistemics
  roles:
  - Mystagogue
  - ForensicMantis
  - Epistemologist
  - Chaplain
  - Cataloguer

- type: department
  id: Silicon
  roles:
  - Cyborg
  - MedicalCyborg
