- type: job
  id: MedicalCyborg
  name: job-name-medical-cyborg
  description: job-desc-cyborg
  playTimeTracker: JobCyborg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 24000
  icon: "Unknown"
  supervisors: "all crew"
  canBeAntag: false
  jobEntity: PlayerCyborgMedical
  startingGear: CyborgGear # for char preview only
