- type: job
  id: SalvageTechnician
  name: job-name-salvage-technician
  description: job-description-salvage-technician
  icon: "ShaftMiner"
  startingGear: SalvageTechnicianGear
  playTimeTracker: JobStationEngineer
  antagAdvantage: 3
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1800
  supervisors: "the chief engineer"
  access:
  - Salvage
  - Engineering
  - Maintenance
  - External

- type: startingGear
  id: SalvageTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvageTechPDA
    ears: ClothingHeadsetEngineering
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
