- type: job
  id: SalvageTechnician
  name: "salvage technician"
  icon: "ShaftMiner"
  startingGear: SalvageTechnicianGear
  departments:
  - Engineering
  supervisors: "the chief engineer"
  access:
  - Salvage
  - Engineering
  - Maintenance
  - External

- type: startingGear
  id: SalvageTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvageTechPDA
    ears: ClothingHeadsetEngineering
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
