- type: job
  id: Chaplain
  name: "cleric"
  startingGear: ChaplainGear
  departments:
  - Epistemics
  icon: "Chaplain"
  supervisors: "the mystagogue"
  access:
  - Chapel
  - Research
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackChaplainFilled
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelChaplainFilled
  duffelbag: ClothingBackpackDuffelChaplainFilled
