- type: job
  id: Chaplain
  name: "cleric"
  startingGear: ChaplainGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics
      time: 3600
  playTimeTracker: JobChaplain
  icon: "Chaplain"
  supervisors: "the mystagogue"
  access:
  - Chapel
  - Research
  extendedAccess:
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance
      multiplier: 3

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackChaplainFilled
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelChaplainFilled
  duffelbag: ClothingBackpackDuffelChaplainFilled
