- type: job
  id: Detective
  name: "detective"
  startingGear: DetectiveGear
  departments:
  - Civilian
  - Security
  icon: "Detective"
  supervisors: "the head of personnel"
  access:
  - Research
  - Brig
  - Detective
  - Maintenance

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackDetectiveFilled
    shoes: ClothingShoesColorBlack
    id: DetectivePDA
    outerClothing: ClothingOuterCoatDetective
    ears: ClothingHeadsetService
    head: ClothingHeadHatFedoraBrown
    pocket1: RevolverInspector
    pocket2: ForensicScanner
  innerclothingskirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelDetectiveFilled
  duffelbag: ClothingBackpackDuffelDetectiveFilled
