- type: job
  id: Lawyer
  name: job-name-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  icon: "Lawyer"
  antagAdvantage: 2 #Starting sec access and radio
  supervisors: job-supervisors-hop
  access:
  - Service
  - Brig

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackBriefcaseFilled
    shoes: ClothingShoesColorBlack
    pocket1: HyperlinkBookSpaceLaw
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  innerclothingskirt: ClothingUniformJumpskirtLawyerBlack
