- type: job
  id: Mime
  name: "mime"
  startingGear: MimeGear
  departments:
  - Entertainment
  icon: "Mime"
  supervisors: "the head of personnel"
  access:
  - Theatre
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers

- type: startingGear
  id: MimeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMime
    back: ClothingBackpackMimeFilled
    head: ClothingHeadHatBeret
    belt: ClothingBeltSuspenders
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    mask: ClothingMaskMime
    id: MimePDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtMime
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelMimeFilled
