- type: job
  id: Detective
  name: "areopagite"
  startingGear: DetectiveGear
  departments:
  - Epistemics
  icon: "Detective"
  supervisors: "the mystagogue"
  access:
  - Research
  - Brig
  - Detective
  - Maintenance

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackDetectiveFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadAreopagite
    id: DetectivePDA
    outerClothing: ClothingOuterSuitAreopagite
    ears: ClothingHeadsetScience
    pocket1: WeaponRevolverInspector
    pocket2: ForensicScanner
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelDetectiveFilled
  duffelbag: ClothingBackpackDuffelDetectiveFilled
