- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingHeadHatWarden
      - id: ClothingHeadHatBeretWarden
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingUniformJumpsuitSecFormal
        prob: 0.1
      - id: ClothingHeadHelmetBasic
      - id: ClothingHeadHelmetInsulated
        prob: 0.4
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: BoxForensicPad

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: ClothingMaskGas

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunVector
  name: vector safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunVector
      amount: 2
    - id: MagazineMagnumSubMachineGun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3

