- type: startingGear
  id: UristChangelingOutfit
  equipment:
    back: ClothingBackpackChameleonFill
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorChangeling
    shoes: ClothingShoesChameleonNoSlips
    head: ClothingHeadHelmetLing
    mask: ClothingMaskGasVoiceMasker
